spring:
  application:
    name: gridcapa-core-cc-post-processing
  cloud:
    function:
      definition: consumeTaskDtoUpdate

core-cc-post-processing:
  process:
    tag: CORE_CC
    timezone: CET
  pisa:
    aligned-ra-names:
      - PRA_HVDC_GILE_PIOSSASCO_1 + PRA_HVDC_GILE_PIOSSASCO_2
      - CRA_HVDC_GILE_PIOSSASCO_1 + CRA_HVDC_GILE_PIOSSASCO_2
    link1:
      node-fr: FFG.IL12
      node-it: FFG.IL11
      fictive-lines:
        - FFG.IL12 FFG.IL11 1
        - FFG.IL12 FFG.IL11 2
        - FFG.IL12 FFG.IL11 3
      pra-name: PRA_HVDC_GILE_PIOSSASCO_1
    link2:
      node-fr: FFG.IL14
      node-it: FFG.IL13
      fictive-lines:
        - FFG.IL14 FFG.IL13 1
        - FFG.IL14 FFG.IL13 2
        - FFG.IL14 FFG.IL13 3
      pra-name: PRA_HVDC_GILE_PIOSSASCO_2
