spring:
  application:
    name: gridcapa-core-cc-post-processing
  cloud:
    function:
      definition: consumeTaskDtoUpdate

core-cc-post-processing:
  process:
    tag: CORE_CC
    timezone: CET
