logback:
  amqp:
    exchange: task-manager-logs-exchange
    routing-key: "#"
spring:
  application:
    name: gridcapa-core-cc-post-processing
  rabbitmq:
    host: localhost
    username: gridcapa
    password: gridcapa
    port: 5672
  cloud:
    stream:
      bindings:
        default:
          group: core-cc-post-processing
        consumeTaskDtoUpdate-in-0:
          destination: core-cc-task-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
        bindings:
          consumeTaskDtoUpdate-in-0:
            consumer:
              binding-routing-key: status
    function:
      definition: consumeTaskDtoUpdate

core-cc-post-processing:
  url:
    task-manager-timestamp-url: http://localhost:8080/tasks/
    task-manager-business-date-url: http://localhost:8080/tasks/businessdate/
  process:
    tag: CORE_CC
    timezone: CET

minio-adapter:
  bucket: gridcapa
  base-path: CORE/CC
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000/
